"""
Cấu hình toàn cục cho hệ thống identify-behavior
"""
import os
from config.performance_config import PerformanceConfig
from config.model_config import ModelConfig
    
# Chuyển đổi pixel -> mét cho dữ liệu tracking
PIXEL_TO_METER = 0.05
HOMOGRAPHY_MATRIX = None
TRACKING_EXPORT_ENABLED = True
TRACKING_EXPORT_PATH = "./tracking_data.csv"
TRACKING_EXPORT_JSON = "./tracking_data.json"

# link
FIRE_MODEL_PATH = "./models/fire.pt"
ACCIDENT_MODEL_PATH = "./models/accident.pt"
COCO_MODEL = "yolov8n.pt"

# Chế độ phát hiện: smoke + vehicle collision + accident
ENABLE_PERSON_DETECTION = True
ENABLE_COLLISION_FIGHT_DETECTION = True
ENABLE_FIRE_DETECTION = True
ENABLE_ACCIDENT_DETECTION = True
CASCADE_FIRE_COLOR_CHECK = True
CASCADE_ACCIDENT_REQUIRE_VEHICLES = True
PROCESS_EVERY_N_FRAMES = 1

CONF_THRESHOLD = 0.22
VEHICLE_CONF_THRESHOLD = 0.65
SMOKE_CONF = 0.45 
ACCIDENT_CONF = 0.55  
ACCIDENT_BUFFER_FRAMES = 5
ACCIDENT_MIN_AREA_RATIO = 0.016  
ACCIDENT_MIN_WIDTH = 65 
ACCIDENT_MIN_HEIGHT = 40
FIRE_MIN_AREA_RATIO = 0.006

IOU_COLLISION = 0.45
IOU_FIGHT = 0.58          
FIGHT_MIN_PERSONS = 2      
FIGHT_VELOCITY_THRESHOLD = 10 

MAX_TRACK_HISTORY = PerformanceConfig.MAX_TRACK_HISTORY
MAX_LOST_FRAMES = 5

BOUND_GROUND = False
GROUND_Y_MIN = 0.05
GROUND_Y_MAX = 0.98
IMGSZ_SMOKE = 224
IMGSZ_COCO = 640

TRACKING_MAX_DIST = 200
VELOCITY_THRESHOLD = 35   
TRAIN_MIN_ASPECT_RATIO = 2.2  

OUTPUT_DIR = "./imgout"
